{{/*
#
# Copyright (c) 2019 WiTCOM GmbH.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.global.provisionStorageClass }}
{{ $namespace := .Release.Namespace }}
{{ $defaults := .Values.classdefaults}}
{{- range $classConfig := .Values.classes }}
apiVersion: v1
data:
  key: {{ or $classConfig.userSecret $defaults.userSecret | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ or $classConfig.userSecretName $defaults.userSecretName }}
type: kubernetes.io/rbd
{{- end }}
{{- end }}

