apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"zk"},"name":"zk","namespace":"testkafkadeployment"},"spec":{"podManagementPolicy":"OrderedReady","replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"zk"}},"serviceName":"zk-svc","template":{"metadata":{"creationTimestamp":null,"labels":{"app":"zk"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["zk"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"command":["sh","-c","zkGenConfig.sh \u0026\u0026 zkServer.sh start-foreground"],"env":[{"name":"ZK_REPLICAS","value":"2"},{"name":"ZK_HEAP_SIZE","valueFrom":{"configMapKeyRef":{"key":"jvm.heap","name":"zk-cm"}}},{"name":"ZK_TICK_TIME","valueFrom":{"configMapKeyRef":{"key":"tick","name":"zk-cm"}}},{"name":"ZK_INIT_LIMIT","valueFrom":{"configMapKeyRef":{"key":"init","name":"zk-cm"}}},{"name":"ZK_SYNC_LIMIT","valueFrom":{"configMapKeyRef":{"key":"tick","name":"zk-cm"}}},{"name":"ZK_MAX_CLIENT_CNXNS","valueFrom":{"configMapKeyRef":{"key":"client.cnxns","name":"zk-cm"}}},{"name":"ZK_SNAP_RETAIN_COUNT","valueFrom":{"configMapKeyRef":{"key":"snap.retain","name":"zk-cm"}}},{"name":"ZK_PURGE_INTERVAL","valueFrom":{"configMapKeyRef":{"key":"purge.interval","name":"zk-cm"}}},{"name":"ZK_CLIENT_PORT","value":"2181"},{"name":"ZK_SERVER_PORT","value":"2888"},{"name":"ZK_ELECTION_PORT","value":"3888"}],"image":"docker-registry.default.svc:5000/openshift/zookeeper:latest","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["zkOk.sh"]},"failureThreshold":3,"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"k8szk","ports":[{"containerPort":2181,"name":"client","protocol":"TCP"},{"containerPort":2888,"name":"server","protocol":"TCP"},{"containerPort":3888,"name":"leader-election","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["zkOk.sh"]},"failureThreshold":3,"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"requests":{"cpu":"500m","memory":"2Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/zookeeper","name":"datadir"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"updateStrategy":{"type":"OnDelete"},"volumeClaimTemplates":[{"metadata":{"creationTimestamp":null,"name":"datadir"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}}}]}}
  creationTimestamp: null
  generation: 1
  labels:
    app: zk
  name: zk
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zk
  serviceName: zk-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zk
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - sh
        - -c
        - zkGenConfig.sh && zkServer.sh start-foreground
        env:
        - name: ZK_REPLICAS
          value: "2"
        - name: ZK_HEAP_SIZE
          valueFrom:
            configMapKeyRef:
              key: jvm.heap
              name: zk-cm
        - name: ZK_TICK_TIME
          valueFrom:
            configMapKeyRef:
              key: tick
              name: zk-cm
        - name: ZK_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
              key: init
              name: zk-cm
        - name: ZK_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
              key: tick
              name: zk-cm
        - name: ZK_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
              key: client.cnxns
              name: zk-cm
        - name: ZK_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
              key: snap.retain
              name: zk-cm
        - name: ZK_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: purge.interval
              name: zk-cm
        - name: ZK_CLIENT_PORT
          value: "2181"
        - name: ZK_SERVER_PORT
          value: "2888"
        - name: ZK_ELECTION_PORT
          value: "3888"
        image: docker-registry.default.svc:5000/openshift/zookeeper:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - zkOk.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: k8szk
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: server
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - zkOk.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: datadir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: zk-795446c59b
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updateRevision: zk-795446c59b
  updatedReplicas: 2
