apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kafka-0.dev.witcom.services
spec:
  ports:
  - port: 9092
    name: external
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kafka-1.dev.witcom.services
spec:
  ports:
  - port: 9092
    name: external
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
---

